export:
  mongoUri: "mongodb://mongoadmin:secret@localhost:27017/mydatabase?authSource=admin"
  mongoCollection: "products"

import:
  postgresUri: "postgresql://postgres:secret@localhost:5432/products"
  postgresTable: "public.products_raw"

job:
  name: "test"
  start: "2023-12-01T00:00:00Z"
  schedule: 1
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  scheduleUnit: "m"
